### ISSUE TITLE
【制品库-评审会已评审】feat：支持查看仓库用量、目录大小、文件数

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-repo#1063]
1、仓库列表，支持展示目前仓库的用量和仓库下的文件个数
- 仓库用量：仓库下的文件总大小，如 10 PB、123.45 TB
- 文件个数：仓库下存储的文件个数
<img width="600" alt="image" src="https://github.com/TencentBlueKing/bk-repo/assets/54432927/e5f62b7d-338c-4fe3-9e32-a0a685f0ae73">

2、仓库下的文件/目录列表，支持展示目录大小和目录下的文件个数
- 大小：目录下的所有文件总大小（需递归子目录）
- 文件个数：目录下的所有文件数（需递归子目录）
<img width="600" alt="image" src="https://github.com/TencentBlueKing/bk-repo/assets/54432927/fddcef34-db87-4ef5-bf13-cc056d3df52f">

**Comment by EchoQT** [comment]
ok.

**Comment by EchoQT** [comment]
不知道为啥，这个单我找不到approved的状态？就没变更了

**Comment by zacYL** [comment]
[#1012](https://github.com/TencentBlueKing/bk-repo/pull/1065)

**Comment by fayewong-v5** [comment]
已支持
