### ISSUE TITLE
支持蓝鲸平台其他APP界面直接调用 bk-repo 接口上传文件，生成临时下载链接

### ISSUE THREAD

**Issue by jeremylv1992** [TencentBlueKing/bk-repo#118]
**What would you like to be added**:
其他APP前端界面，调用 bk-repo 接口上传大文件，返回临时下载链接（可以设置1小时之类的过期时间，到期自动清理文件也行）

**Why is this needed**:
如果 bk-repo 可以承接大文件上传需求，其他 APP 只需要保留下载链接，或者在后台对应位置再进行文件下载或者转存，整体 SaaS 链路避免传输大文件，这样每个 SaaS 也不需要重复处理大文件上传问题

**Comment by owenlxu** [comment]
已经解决，现有方案支持
