### ISSUE TITLE
gateway监听地址应该为可配置项

### ISSUE THREAD

**Issue by vuuv** [TencentBlueKing/bk-repo#119]
**What happened**:
用户环境不支持ipv6网络栈, 导致报错:
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)

**What you expected to happen**:
https://github.com/TencentBlueKing/bk-repo/blob/master/support-files/templates/gateway%23vhosts%23bkrepo.server.conf
```
server {
  listen __BK_REPO_HTTP_PORT__ default;
  listen [::]:__BK_REPO_HTTP_PORT__ default;
  server_name "__BK_REPO_HOST__";

  listen 8081;
  listen [::]:8081;
```

希望把第二个listen改为配置项. 默认可以为 `[::]`, 也应该通过 charts values 暴露, 以备ipv4单栈用户修改为 `127.0.0.1` 绕过ipv6监听.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- bk-repo version (use `cat VERSION` in installed dir):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by owenlxu** [comment]
已经交付
