### ISSUE TITLE
generic 下载报错NodeNotFoundException打印error日志

### ISSUE THREAD

**Issue by zacYL** [TencentBlueKing/bk-repo#1423]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- bk-repo version (use `cat VERSION` in installed dir):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by cnlkl** [comment]
不支持客户端传的请求头Accpet，再响应错误信息时报`HttpMediaTypeNotAcceptableException`
