### ISSUE TITLE
remotes/origin/release-1.3.31 gradle 编译jra包冲突

### ISSUE THREAD

**Issue by Soulmate102441** [TencentBlueKing/bk-repo#2132]
> Task :common:common-api:compileKotlin FAILED
w: Runtime JAR files in the classpath should have the same version. These files were found in the classpath:
    /home/user/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk8/1.4.32/3302f9ec8a5c1ed220781dbd37770072549bd333/kotlin-stdlib-jdk8-1.4.32.jar (version 1.4)
    /home/user/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-reflect/1.4.32/ce852b166d97f0f1991b5130c2bb02e2ef6c554e/kotlin-reflect-1.4.32.jar (version 1.4)
    /home/user/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.5.32/2e8f666555c2a6bf10ef712be8a738e665132c8/kotlin-stdlib-jdk7-1.5.32.jar (version 1.5)
    /home/user/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.5.32/a1f8a73f899b85e6eb4337dff7e81b8b914bd2c9/kotlin-stdlib-1.5.32.jar (version 1.5)
    /home/user/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.5.32/8befc4a20c17094a148f1409c1bac163bc3ca630/kotlin-stdlib-common-1.5.32.jar (version 1.5)
w: Consider providing an explicit dependency on kotlin-reflect 1.5 to prevent strange errors
w: Some runtime JAR files in the classpath have an incompatible version. Consider removing them from the classpath
e: /local/sdb/bkrepo/bk-repo/src/backend/common/common-api/src/main/kotlin/com/tencent/bkrepo/common/api/util/IpUtils.kt: (30, 21): Symbol is declared in module 'java.base' which does not export package 'sun.net.util'
e: /local/sdb/bkrepo/bk-repo/src/backend/common/common-api/src/main/kotlin/com/tencent/bkrepo/common/api/util/IpUtils.kt: (48, 21): Symbol is declared in module 'java.base' which does not export package 'sun.net.util'
e: /local/sdb/bkrepo/bk-repo/src/backend/common/common-api/src/main/kotlin/com/tencent/bkrepo/common/api/util/IpUtils.kt: (48, 35): Symbol is declared in module 'java.base' which does not export package 'sun.net.util'

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':common:common-api:compileKotlin'.
> Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 8s
17 actionable tasks: 1 executed, 16 up-to-date

**Comment by cnlkl** [comment]
需要使用java 8进行编译
