### ISSUE TITLE
feat：制品列表展示的记录数和批量选择优化

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-repo#2261]
1、流水线仓库/自定义仓库的制品列表，支持单页展示50/100个制品
2、批量选择支持跨页全选和本页反选
1）支持三个操作：本页全选、跨页全选、本页反选
<img width="600" alt="image" src="https://github.com/TencentBlueKing/bk-repo/assets/54432927/5ba762ae-db8c-45cd-8345-2f869e8d6e5d">
2）跨页全选后，展示选中的数据条数，支持清除选择
<img width="600" alt="image" src="https://github.com/TencentBlueKing/bk-repo/assets/54432927/d767b4bd-52b4-4ffe-9231-938c2cdd7eea">
3）表头上的选择图标，根据不同的操作有不同的展示
- 本页全选 <img width="30" alt="image" src="https://github.com/TencentBlueKing/bk-repo/assets/54432927/65164c29-8e7b-4768-92d4-47f85f93a907">
- 跨页全选<img width="30" alt="image" src="https://github.com/TencentBlueKing/bk-repo/assets/54432927/8fcb1011-23b3-4bf7-a9a3-11a22245cb25">
- 跨页全选后，本页反选 ：待补充

4）选中后，批量下载/删除操作对选中项生效

**Comment by lannoy0523** [comment]
与小助手沟通，magicBox的table组件有bug，暂等新版本。

**Comment by lannoy0523** [comment]
issue方法无法解决问题。尝试其他方法重写此部分。
