### ISSUE TITLE
提问: Generic的库文件存储在哪

### ISSUE THREAD

**Issue by Soulmate102441** [TencentBlueKing/bk-repo#2481]
提问: Generic的库文件存储在哪
![2024-08-12 17-53-44屏幕截图](https://github.com/user-attachments/assets/8d2ac6f1-340c-4a5a-85ad-26e13245fb5d)

**Comment by lannoy0523** [comment]
建议查看Storage属性配置。类似于/support-files
/template/#etc#bkrepo#application.yaml 文件中的配置 @Soulmate102441

**Comment by Soulmate102441** [comment]
找到了。谢谢
