### ISSUE TITLE
部署包到OSS的action执行错误

### ISSUE THREAD

**Issue by felixncheng** [TencentBlueKing/bk-repo#25]
gpg: WARNING: unsafe permissions on homedir '/home/runner/.gnupg'
gpg: no valid OpenPGP data found.

**Comment by irwinsun** [comment]
src/backend/buildSrc/build.gradle.kts

需要依赖一下依赖

// 插件使用仓库
repositories {
    mavenLocal()
    if (System.getenv("GITHUB_WORKFLOW") == null) { // 普通环境
        maven(url = "https://mirrors.tencent.com/nexus/repository/maven-public")
        maven(url = "https://mirrors.tencent.com/nexus/repository/gradle-plugins/")
    } else { // GitHub Action 环境
        mavenCentral()
        gradlePluginPortal()
    }
}

**Comment by irwinsun** [comment]
上面适配Tencent环境，
下面适配GithubActions
