### ISSUE TITLE
MongoDbBatchJob每次执行都会查出所有字段

### ISSUE THREAD

**Issue by cnlkl** [TencentBlueKing/bk-repo#597]
**What happened**:

MongoDbBatchJob从entityClass中获取fields为空，导致每次都会将数据全量查出，而不是只查出需要的数据

**What you expected to happen**:

只查出需要的字段

**Anything else we need to know?**:

[Kotlin Backing-Fields](https://kotlinlang.org/docs/properties.html#backing-fields)

**Comment by felixncheng** [comment]
需要修改为使用kotlin class获取字段

**Comment by felixncheng** [comment]
已解决
