### ISSUE TITLE
 generic 仓库支持批量下载功能

### ISSUE THREAD

**Issue by gujunling** [TencentBlueKing/bk-repo#778]
**What would you like to be added**:
generic 仓库支持批量下载功能
**Why is this needed**:

**Comment by scplsy** [comment]
在原有的批量下载接口基础之上做了这些改动：
1. batchDownload新增POST请求类型（前端GET请求无法发送请求体）。
2. 可以同时选择文件和目录节点，空目录也会一同下载。
3. 修复了下载多个节点时，公共目录层数过多的问题。
4. 下载的多个节点没有公共目录（公共目录为根目录）时，在zip包添加以仓库名命名的顶层目录，确保解压缩出来只有一个目录。
